services:
  - type: web
    name: procureiq-springboot
    runtime: maven
    buildCommand: ./mvnw clean package -Dmaven.repo.local=./.m2/repository -DskipTests
    startCommand: java -jar target/springboot-app-0.0.1-SNAPSHOT.jar
    cacheDirectories:
      - .m2/repository
